graph TD
A[Talk to me]
B[Show me the data!]
A --> |I'm your shadow for a day or two| B
C[Gio's 12-Question Value Survey]
D[Show me how is done]
B --> |Walk me through it please| D
C --> A
G{Do we have enough context?}
D --> G
F[Let's keep talking, and draft the concept together]
G --> |Yes| F
G --> |No| A